[device.jetson_hdf5]
enabled = true
device = "external"
exec = "/usr/local/bin/hdf5_connector"
args = " " #should have a path to buffer later 
center_freq = 137000000
srate = 2083334
short_name = "Jetson IQ"
long_name = "Live IQ buffer from Jetson"
iqfmt = "float32"  
